#cloud-config
hostname: ubuntu-noble-all
manage_etc_hosts: true
fqdn: ubuntu-noble-all
locale: en_NZ

user: campbellrehu
password: $5$tbA4ZZwA$KmgHcPjleEa8TGxEmm6fpRjpwSsSU1QNRvVlruQtAnD
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIElYj3+Q3vgQaJ6Bs7g5JeIJIBz/w52iqnipI5O3do8F campbellrehu

chpasswd:
  list: |
    root:password
  expire: false

write_files:
  - path: /etc/sudoers.d/cloud-init
    content: |
      Defaults !requiretty

package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent

runcmd:
  - sed -i 's/^#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
  - sed -i 's/^#PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config
  - sed -i -e 's/^GSSAPIAuthentication yes/GSSAPIAuthentication no/g' /etc/ssh/sshd_config
  - sed -i -e 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
  - systemctl restart sshd
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
